
#import "CIFiltersDef.h"
NSArray* g_filtersorts = nil;
NSArray<ParamCIFilterSort*>* g_paramfiltersorts = nil;
@implementation CIFiltersDef
+(NSArray*)getFilterSorts
{
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        g_filtersorts = @[
                          @{
                              @"key":kCIFilterSort_CICategoryBlur,
                              @"name":@"模糊处理",
                              @"filters":@[
                                      @{
                                          @"key":kCIFilter_CIBoxBlur,
                                          @"name":@"盒形卷积"
                                          },
                                      @{
                                          @"key":kCIFilter_CIDiscBlur,
                                          @"name":@"盘形卷积"
                                          },
                                      @{
                                          @"key":kCIFilter_CIGaussianBlur,
                                          @"name":@"高斯模糊"
                                          },
                                      @{
                                          @"key":kCIFilter_CIMaskedVariableBlur,
                                          @"name":@"黑白反显"
                                          },
                                      @{
                                          @"key":kCIFilter_CIMedianFilter,
                                          @"name":@"中值降噪"
                                          },
                                      @{
                                          @"key":kCIFilter_CIMotionBlur,
                                          @"name":@"动感相机"
                                          },
                                      @{
                                          @"key":kCIFilter_CINoiseReduction,
                                          @"name":@"差值降噪"
                                          },
                                      @{
                                          @"key":kCIFilter_CIZoomBlur,
                                          @"name":@"变焦摄影"
                                          },
                                      ]
                              },
                          @{
                              @"key":kCIFilterSort_CICategoryColorAdjustment,
                              @"name":@"色彩调整",
                              @"filters":@[
                                      @{
                                          @"key":kCIFilter_CIColorClamp,
                                          @"name":@"区间变色"
                                          },
                                      @{
                                          @"key":kCIFilter_CIColorControls,
                                          @"name":@"显示控制"
                                          },
                                      @{
                                          @"key":kCIFilter_CIColorMatrix,
                                          @"name":@"矩阵变换"
                                          },
                                      @{
                                          @"key":kCIFilter_CIColorPolynomial,
                                          @"name":@"多阶变换"
                                          },
                                      @{
                                          @"key":kCIFilter_CIExposureAdjust,
                                          @"name":@"曝光调整"
                                          },
                                      @{
                                          @"key":kCIFilter_CIGammaAdjust,
                                          @"name":@"灰度平滑"
                                          },
                                      @{
                                          @"key":kCIFilter_CIHueAdjust,
                                          @"name":@"色调旋转"
                                          },
                                      @{
                                          @"key":kCIFilter_CILinearToSRGBToneCurve,
                                          @"name":@"线性标化"
                                          },
                                      @{
                                          @"key":kCIFilter_CISRGBToneCurveToLinear,
                                          @"name":@"标准线化"
                                          },
                                      @{
                                          @"key":kCIFilter_CITemperatureAndTint,
                                          @"name":@"色温调整"
                                          },
                                      @{
                                          @"key":kCIFilter_CIToneCurve,
                                          @"name":@"色调曲线"
                                          },
                                      @{
                                          @"key":kCIFilter_CIVibrance,
                                          @"name":@"色值抖动"
                                          },
                                      @{
                                          @"key":kCIFilter_CIWhitePointAdjust,
                                          @"name":@"白平衡化"
                                          },
                                      ]
                              },
                          @{
                              @"key":kCIFilterSort_CICategoryColorEffect,
                              @"name":@"色彩效果",
                              @"filters":@[
                                      @{
                                          @"key":kCIFilter_CIColorCrossPolynomial,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIColorCube,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIColorCubeWithColorSpace,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIColorInvert,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIColorMap,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIColorMonochrome,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIColorPosterize,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIFalseColor,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIMaskToAlpha,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIMaximumComponent,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIMinimumComponent,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIPhotoEffectChrome,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIPhotoEffectFade,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIPhotoEffectInstant,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIPhotoEffectMono,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIPhotoEffectNoir,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIPhotoEffectProcess,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIPhotoEffectTonal,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIPhotoEffectTransfer,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CISepiaTone,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIVignette,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIVignetteEffect,
                                          @"name":@""
                                          },
                                      ]
                              },
                          @{
                              @"key":kCIFilterSort_CICategoryCompositeOperation,
                              @"name":@"复合操作",
                              @"filters":@[
                                      @{
                                          @"key":kCIFilter_CIAdditionCompositing,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIColorBlendMode,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIColorBurnBlendMode,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIColorDodgeBlendMode,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIDarkenBlendMode,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIDifferenceBlendMode,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIDivideBlendMode,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIExclusionBlendMode,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIHardLightBlendMode,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIHueBlendMode,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CILightenBlendMode,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CILinearBurnBlendMode,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CILinearDodgeBlendMode,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CILuminosityBlendMode,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIMaximumCompositing,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIMinimumCompositing,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIMultiplyBlendMode,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIMultiplyCompositing,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIOverlayBlendMode,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIPinLightBlendMode,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CISaturationBlendMode,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIScreenBlendMode,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CISoftLightBlendMode,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CISourceAtopCompositing,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CISourceInCompositing,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CISourceOutCompositing,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CISourceOverCompositing,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CISubtractBlendMode,
                                          @"name":@""
                                          },
                                      ]
                              },
                          @{
                              @"key":kCIFilterSort_CICategoryDistortionEffect,
                              @"name":@"变形效果",
                              @"filters":@[
                                      @{
                                          @"key":kCIFilter_CIBumpDistortion,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIBumpDistortionLinear,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CICircleSplashDistortion,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CICircularWrap,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIDroste,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIDisplacementDistortion,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIGlassDistortion,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIGlassLozenge,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIHoleDistortion,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CILightTunnel,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIPinchDistortion,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIStretchCrop,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CITorusLensDistortion,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CITwirlDistortion,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIVortexDistortion,
                                          @"name":@""
                                          },
                                      ]
                              },
                          @{
                              @"key":kCIFilterSort_CICategoryGenerator,
                              @"name":@"生成器",
                              @"filters":@[
                                      @{
                                          @"key":kCIFilter_CIAztecCodeGenerator,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CICheckerboardGenerator,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CICode128BarcodeGenerator,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIConstantColorGenerator,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CILenticularHaloGenerator,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIPDF417BarcodeGenerator,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIQRCodeGenerator,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIRandomGenerator,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIStarShineGenerator,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIStripesGenerator,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CISunbeamsGenerator,
                                          @"name":@""
                                          },
                                      ]
                              },
                          @{
                              @"key":kCIFilterSort_CICategoryGeometryAdjustment,
                              @"name":@"几何调整",
                              @"filters":@[
                                      @{
                                          @"key":kCIFilter_CIAffineTransform,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CICrop,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CILanczosScaleTransform,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIPerspectiveCorrection,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIPerspectiveTransform,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIPerspectiveTransformWithExtent,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIStraightenFilter,
                                          @"name":@""
                                          },
                                      ]
                              },
                          @{
                              @"key":kCIFilterSort_CICategoryGradient,
                              @"name":@"渐变调整",
                              @"filters":@[
                                      @{
                                          @"key":kCIFilter_CIGaussianGradient,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CILinearGradient,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIRadialGradient,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CISmoothLinearGradient,
                                          @"name":@""
                                          },
                                      ]
                              },
                          @{
                              @"key":kCIFilterSort_CICategoryHalftoneEffect,
                              @"name":@"半色网屏",
                              @"filters":@[
                                      @{
                                          @"key":kCIFilter_CICircularScreen,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CICMYKHalftone,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIDotScreen,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIHatchedScreen,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CILineScreen,
                                          @"name":@""
                                          },
                                      ]
                              },
                          @{
                              @"key":kCIFilterSort_CICategoryReduction,
                              @"name":@"像素弱化",
                              @"filters":@[
                                      @{
                                          @"key":kCIFilter_CIAreaAverage,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIAreaHistogram,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIRowAverage,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIColumnAverage,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIHistogramDisplayFilter,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIAreaMaximum,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIAreaMinimum,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIAreaMaximumAlpha,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIAreaMinimumAlpha,
                                          @"name":@""
                                          },
                                      ]
                              },
                          @{
                              @"key":kCIFilterSort_CICategorySharpen,
                              @"name":@"图像锐化",
                              @"filters":@[
                                      @{
                                          @"key":kCIFilter_CISharpenLuminance,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIUnsharpMask,
                                          @"name":@""
                                          },
                                      ]
                              },
                          @{
                              @"key":kCIFilterSort_CICategoryStylize,
                              @"name":@"风格添加",
                              @"filters":@[
                                      @{
                                          @"key":kCIFilter_CIBlendWithAlphaMask,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIBlendWithMask,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIBloom,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIComicEffect,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIConvolution3X3,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIConvolution5X5,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIConvolution7X7,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIConvolution9Horizontal,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIConvolution9Vertical,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CICrystallize,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIDepthOfField,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIEdges,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIEdgeWork,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIGloom,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIHeightFieldFromMask,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIHexagonalPixellate,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIHighlightShadowAdjust,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CILineOverlay,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIPixellate,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIPointillize,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIShadedMaterial,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CISpotColor,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CISpotLight,
                                          @"name":@""
                                          },
                                      ]
                              },
                          @{
                              @"key":kCIFilterSort_CICategoryTileEffect,
                              @"name":@"网格处理",
                              @"filters":@[
                                      @{
                                          @"key":kCIFilter_CIAffineClamp,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIAffineTile,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIEightfoldReflectedTile,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIFourfoldReflectedTile,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIFourfoldRotatedTile,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIFourfoldTranslatedTile,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIGlideReflectedTile,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIKaleidoscope,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIOpTile,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIParallelogramTile,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIPerspectiveTile,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CISixfoldReflectedTile,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CISixfoldRotatedTile,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CITriangleKaleidoscope,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CITriangleTile,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CITwelvefoldReflectedTile,
                                          @"name":@""
                                          },
                                      ]
                              },
                          @{
                              @"key":kCIFilterSort_CICategoryTransition,
                              @"name":@"多图过渡",
                              @"filters":@[
                                      @{
                                          @"key":kCIFilter_CIAccordionFoldTransition,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIBarsSwipeTransition,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CICopyMachineTransition,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIDisintegrateWithMaskTransition,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIDissolveTransition,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIFlashTransition,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIModTransition,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIPageCurlTransition,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIPageCurlWithShadowTransition,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CIRippleTransition,
                                          @"name":@""
                                          },
                                      @{
                                          @"key":kCIFilter_CISwipeTransition,
                                          @"name":@""
                                          },
                                      ]
                              }
                          ];
    });
    return g_filtersorts;
}
+(NSArray*)getParamFilterSorts
{
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        NSMutableArray<ParamCIFilterSort*>* paramsorts = [[NSMutableArray alloc]init];
        NSArray* sorts = [CIFiltersDef getFilterSorts];
        for (NSDictionary* dic in sorts)
        {
            ParamCIFilterSort* sort = [[ParamCIFilterSort alloc]init];
            [sort setValuesForKeysWithDictionary:dic];
            [paramsorts addObject:sort];
        }
        g_paramfiltersorts = paramsorts;
    });
    return g_paramfiltersorts;
}
+(NSArray*)getFiltersWithSortkey:(NSString*)sortkey
{
    if (!sortkey)
    {
        return nil;
    }
    NSArray* sorts = [CIFiltersDef getFilterSorts];
    for (NSDictionary* dic in sorts)
    {
        NSString* key = [dic valueForKey:@"key"];
        if ([key isEqualToString:sortkey])
        {
            NSArray* filters = [dic valueForKey:@"filters"];
            return filters;
        }
    }
    return nil;
}
+(NSArray*)getParamFiltersWithSortkey:(NSString*)sortkey
{
    if (!sortkey)
    {
        return nil;
    }
    NSArray* sorts = [CIFiltersDef getParamFilterSorts];
    for (ParamCIFilterSort* sort in sorts)
    {
        if ([sort.key isEqualToString:sortkey])
        {
            return sort.filters;
        }
    }
    return nil;
}
@end

@implementation ParamCIFilter
@end

@implementation ParamCIFilterSort : NSObject
-(void)setValue:(id)value forKey:(NSString *)key
{
    if ([key isEqualToString:@"filters"])
    {
        NSArray* array = value;
        NSMutableArray<ParamCIFilter*>* filters = [[NSMutableArray alloc]init];
        for (NSDictionary* dic in array)
        {
            ParamCIFilter* filter = [[ParamCIFilter alloc]init];
            [filter setValuesForKeysWithDictionary:dic];
            [filters addObject:filter];
        }
        self.filters = filters;
    }else
    {
        [super setValue:value forKey:key];
    }
}
@end
